---
- hosts: all
  become: yes
  gather_facts: yes

  vars:

  tasks:


  - name: install needed dependencies
    yum:
      name: "{{item}}"
      state: installed
      update_cache: True
    with_items:
      - git
      - vim
      - yum-utils
      - docker
      - unzip
      - kernel-devel
      - zsh

  - name: enable docker
    systemd:
      name: docker
      state: started
      enabled: True

  - name: pip install packages
    pip: name={{item}}
    with_items:
      - awscli

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.9.3/terraform_0.9.3_linux_amd64.zip?_ga=1.5946996.615959731.1492784778
      dest: /usr/local/bin
      remote_src: True

  - name: Cloning  oh-my-zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: ~/.oh-my-zsh
    become: no

  - name: Creating new ~/.zshrc
    copy:
      src: templates/.zshrc
      dest: ~/.zshrc
    become: no

  - name: update vagrant user
    user:
      name: vagrant
      shell: /bin/zsh
